import React,{useState} from 'react';
import {ArrowRightIcon,FileTextIcon,ChevronRightIcon,PlayIcon,SpeakerLoudIcon,DrawingPinIcon,RocketIcon,Share2Icon,CheckIcon,Cross2Icon,ReaderIcon,PlusIcon} from '@radix-ui/react-icons';
import {categories,membersFor,reportFor} from './collections';
import SynapseField from './SynapseField';
const icons={Films:PlayIcon,Music:SpeakerLoudIcon,Hobbies:DrawingPinIcon,Projects:RocketIcon};
export default function Collections({notes,originals,onNote,onGraph,onAction,reduced}){
const [category,setCategory]=useState('Projects'),[states,setStates]=useState(()=>{try{return JSON.parse(localStorage.getItem('pure.actions.v1'))||{}}catch{return {}}}),[showAll,setShowAll]=useState(false),[storageError,setStorageError]=useState('');
const members=membersFor(notes,category),report=reportFor(notes,category,originals),Icon=icons[category];
function setAction(id,state){const next={...states,[id]:state};try{localStorage.setItem('pure.actions.v1',JSON.stringify(next));setStates(next);setStorageError('')}catch{setStorageError('Could not save your action preference.')}}
function sources(ids){return <div className="sources">{ids.map(id=>{const n=notes.find(n=>n.id===id);return n&&<button key={id} onClick={()=>onNote(id)}><FileTextIcon/>{n.title}<ChevronRightIcon/></button>})}</div>}
return <div className="intelligence-page"><section className="collection-lead"><div className="lead-copy"><span className="terminal-label"><span className="live-tick"/> memory / synthesis</span><h2>Something is taking shape.</h2><p>残した言葉から、わかること。<br/>ここから、試せること。</p><div className="analysis-disclosure"><span>ANALYSIS PREVIEW</span>サンプルの分析結果 · AI未接続</div></div><div className="neural-art"><SynapseField variant="collection" reduced={reduced}/><span className="art-caption">fragments → patterns → possibilities</span></div></section>
<div className="genre-tabs" role="tablist" aria-label="Collection genres">{categories.map(c=>{const I=icons[c.id],count=membersFor(notes,c.id).length;return <button key={c.id} role="tab" aria-selected={category===c.id} className={category===c.id?'selected':''} onClick={()=>{setCategory(c.id);setShowAll(false)}}><I/><span>{c.id}</span><small>{String(count).padStart(2,'0')}</small></button>})}</div>
<section className="genre-report" key={category} aria-label={category+' analysis'}><div className="report-heading"><div className="report-id"><Icon/><span>{category}</span><small>{members.length} notes · local preview</small></div><button className="text-button" onClick={()=>onGraph(members[0]?.id)}><Share2Icon/>Explore connections</button></div>
{report.available?<><div className="synthesis"><div className="section-number">01<span>SUMMARY</span></div><div><h3>{report.headline}</h3><p>{report.summary}</p><details><summary>View {report.sources.length} source notes<ChevronRightIcon/></summary>{sources(report.sources)}</details></div></div><div className="synthesis observation"><div className="section-number">02<span>PATTERN</span></div><div><span className="inference-label">Interpretation, not a fact</span><p>{report.observation}</p>{sources(report.evidence)}</div></div><div className="action-section"><div className="section-number">03<span>NEXT STEPS</span></div><div className="action-content"><div className="action-heading"><h3>A small next step.</h3><span>選んだものだけ、進める。</span></div>{report.actions.filter(a=>states[a.id]!=='dismissed').map(a=><article className={'action '+(states[a.id]==='done'?'done':'')} key={a.id}><div className="action-top"><span className="action-kind">{a.kind}</span><button className="icon-button" aria-label={'Dismiss '+a.title} onClick={()=>setAction(a.id,'dismissed')}><Cross2Icon/></button></div><h4>{a.title}</h4><p>{a.why}</p>{sources(a.sources)}<div className="action-footer"><button className="start-action" onClick={()=>onAction(a,category)}><PlusIcon/>Start a note<ArrowRightIcon/></button><button className="text-button" onClick={()=>setAction(a.id,states[a.id]==='done'?null:'done')}><CheckIcon/>{states[a.id]==='done'?'Done · undo':'Mark done'}</button></div></article>)}{report.actions.some(a=>states[a.id]==='dismissed')&&<button className="restore-actions" onClick={()=>{const next={...states};report.actions.forEach(a=>{if(next[a.id]==='dismissed')delete next[a.id]});try{localStorage.setItem('pure.actions.v1',JSON.stringify(next));setStates(next)}catch{setStorageError('Could not restore suggestions.')}}}>Restore hidden suggestions</button>}</div></div><div className="open-question"><span>STILL OPEN</span><p>{report.question}</p></div></>:<div className="analysis-empty"><ReaderIcon/><h3>{members.length?'Ready for a closer look.':'A new collection starts with a note.'}</h3><p>{members.length?'新しいメモ、または編集されたメモがあるため、以前の分析サンプルは表示していません。実際の分析にはAI接続が必要です。':'このジャンルの材料がまだありません。内容が集まってから、まとめや提案を作ります。'}</p></div>}
{storageError&&<p className="error" role="alert">{storageError}</p>}<div className="source-archive"><button onClick={()=>setShowAll(!showAll)}><FileTextIcon/>Source notes <span>{members.length}</span><ChevronRightIcon className={showAll?'rotate':''}/></button>{showAll&&<div>{members.map(n=><button className="archive-note" key={n.id} onClick={()=>onNote(n.id)}><span>{n.title}</span><p>{n.text}</p><ArrowRightIcon/></button>)}</div>}</div><p className="classification-note">このプレビューの分類は単語の一致による仮分類です。一つのメモが複数のジャンルに入ることがあります。追加メモのAI解析はまだ行いません。</p></section></div>
}
