import React, {useState, useEffect, useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {FileTextIcon, LayersIcon, MagnifyingGlassIcon, GearIcon, PlusIcon, Cross2Icon, ArrowRightIcon, ArrowLeftIcon, Share2Icon, GridIcon, MinusIcon, EnterFullScreenIcon, Pencil1Icon, CheckIcon, ImageIcon, DownloadIcon, MixerHorizontalIcon, ClockIcon, ChevronRightIcon, LightningBoltIcon} from '@radix-ui/react-icons';
import './style.css';
import Collections from './Collections.jsx';
import SynapseField from './SynapseField';
import {musicSamples} from './collections';
const KEY='pure.prototype.notes.v1', DRAFT='pure.prototype.draft.v1';
const seeds=[
{id:'rain',text:'雨の日だけ開く喫茶店があったら、少し楽しみになる。',title:'雨の日だけ開く喫茶店',group:'Quiet places',date:'2026-09-27T18:42:00',x:450,y:330},
{id:'film',text:'PERFECT DAYSを観た。毎日同じことを繰り返す生活にも豊かさがある気がした。\n\nあの静けさが、ずっと残っている。',title:'PERFECT DAYSの感想',group:'Films & stories',date:'2026-09-27T16:10:00',x:255,y:460},
{id:'cafe',text:'小さな喫茶店と、街の余白。\n\n雨の音とコーヒーの香り。それだけで十分かもしれない。こういう場所を、近所にも見つけたい。',title:'小さな喫茶店と、街の余白',group:'Quiet places',date:'2026-09-27T12:35:00',x:700,y:382},
{id:'quiet',text:'静かな場所だと、考えがまとまる。\n頭の中が、少しずつ整う。',title:'静かな場所だと考えがまとまる',group:'Quiet places',date:'2026-09-25T09:15:00',x:480,y:535},
{id:'alone',text:'一人で過ごす場所。\nここにいると、少しだけ素直になれる。',title:'一人で過ごす場所',group:'Quiet places',date:'2026-09-22T15:30:00',x:300,y:242},
{id:'habit',text:'気持ちのよい習慣を続ける仕組みを作りたい。\n記録すること自体が、ちょっと楽しみになるような。',title:'習慣アプリのアイデア',group:'Things to make',date:'2026-09-23T21:10:00',x:755,y:563},
{id:'coffee',text:'朝のコーヒーが、今日をつくる。\n豆を挽く音、立ちのぼる湯気、最初のひと口。',title:'朝のコーヒー',group:'Small pleasures',date:'2026-09-26T08:10:00',x:220,y:125},
{id:'season',text:'窓を開けたら、少しだけ秋の匂いがした。',title:'季節の匂い',group:'Small pleasures',date:'2026-09-24T07:25:00',x:125,y:170},
{id:'walk',text:'帰り道、いつもと違う角を曲がったら、小さな本屋があった。',title:'帰り道の風景',group:'Small pleasures',date:'2026-09-20T19:00:00',x:165,y:238},
{id:'cinema',text:'夜の映画館が好き。映画が終わって、街に戻るまでの時間も。',title:'夜の映画館',group:'Films & stories',date:'2026-09-21T22:00:00',x:840,y:205},
{id:'watch',text:'「パターソン」を観たい。日々を言葉にする映画。',title:'パターソンを観たい',group:'Films & stories',date:'2026-09-19T17:30:00',x:730,y:145},
{id:'book',text:'好きな文章だけを集めて、小さな本にしたい。',title:'小さな本を作りたい',group:'Things to make',date:'2026-09-18T20:10:00',x:700,y:680},
{id:'room',text:'部屋の植物に水をあげた。葉の色が濃くなった気がする。',title:'部屋の植物',group:'Things to make',date:'2026-09-26T21:20:00',x:850,y:650},
{id:'library',text:'図書館の窓際。誰も急いでいない場所。',title:'図書館の窓際',group:'Quiet places',date:'2026-09-17T14:00:00',x:230,y:655},
{id:'sea',text:'海の近くで暮らすことを、たまに考える。',title:'海の近く',group:'Quiet places',date:'2026-09-16T12:00:00',x:130,y:610}
];
const edges=[['rain','film'],['rain','cafe'],['rain','quiet'],['rain','alone'],['rain','habit'],['alone','quiet'],['coffee','season'],['season','walk'],['walk','coffee'],['alone','walk'],['cinema','watch'],['watch','film'],['habit','book'],['habit','room'],['book','room'],['library','sea'],['library','quiet'],['coffee','rain']];
const groupNames=['Quiet places','Small pleasures','Films & stories','Things to make'];
const descriptions={'Quiet places':'一人で過ごす場所、心が落ち着く時間。','Small pleasures':'日常の中に見つけた、小さな豊かさ。','Films & stories':'観たもの、読みたいもの、残った余韻。','Things to make':'いつか形にしてみたい、思いつきの種。'};
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function Mark({className=''}){return <svg className={'mark '+className} viewBox="0 0 90 60" fill="none" aria-hidden="true"><path fill="currentColor" d="M3 46C19 40 30 29 44 35C36 39 40 44 50 46C62 50 72 43 87 45C62 48 60 58 38 51C24 46 19 43 3 46Z"/><path d="M43 39C58 29 53 9 62 5M48 43C59 36 64 31 69 22" stroke="currentColor" strokeWidth="1.5"/><ellipse cx="63" cy="5" rx="3" ry="5" transform="rotate(35 63 5)" fill="currentColor"/><ellipse cx="70" cy="21" rx="2.6" ry="4" transform="rotate(35 70 21)" fill="currentColor"/></svg>}
function App(){
const [notes,setNotes]=useState(()=>{const saved=read(KEY,seeds);return [...saved,...musicSamples.filter(n=>!saved.some(s=>s.id===n.id))]}),[page,setPage]=useState('Collections'),[mode,setMode]=useState('list'),[selected,setSelected]=useState(null),[modal,setModal]=useState(null),[draft,setDraft]=useState(()=>{const d=read(DRAFT,'');return typeof d==='string'?d:d.text||''}),[query,setQuery]=useState(''),[toast,setToast]=useState(''),[boot,setBoot]=useState(!sessionStorage.getItem('pure.boot')),[reduced,setReduced]=useState(()=>read('pure.motion',false)),[filter,setFilter]=useState(null),[view,setView]=useState({x:0,y:0,z:1}),[hover,setHover]=useState(null),[editing,setEditing]=useState(()=>read(DRAFT,{})?.editing||null),[error,setError]=useState(''),[draftOrigin,setDraftOrigin]=useState(()=>read(DRAFT,{})?.origin||null);
const inputRef=useRef(null), opener=useRef(null), drag=useRef(null), graphRef=useRef(null);
const active=notes.find(n=>n.id===selected); const linked=active?(active.origin?.sourceIds?active.origin.sourceIds.map(id=>notes.find(n=>n.id===id)).filter(Boolean):edges.filter(e=>e.includes(active.id)).map(e=>notes.find(n=>n.id===e.find(id=>id!==active.id))).filter(Boolean)):[];
const shown=notes.filter(n=>(!filter||n.group===filter)&&(!query||n.text.toLowerCase().includes(query.toLowerCase())||n.title.toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>new Date(b.date)-new Date(a.date));
useEffect(()=>{const t=setTimeout(()=>{setBoot(false);sessionStorage.setItem('pure.boot','1')},1100);return()=>clearTimeout(t)},[]);
useEffect(()=>{document.documentElement.dataset.reduced=reduced;try{localStorage.setItem('pure.motion',JSON.stringify(reduced))}catch{}},[reduced]);
useEffect(()=>{try{localStorage.setItem(DRAFT,JSON.stringify({text:draft,origin:draftOrigin,editing}))}catch{}},[draft,draftOrigin,editing]);
useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),3000);return()=>clearTimeout(t)}},[toast]);
function open(type){opener.current=document.activeElement;setError('');setModal(type);setTimeout(()=>inputRef.current?.focus(),30)}
function close(){setModal(null);setError('');requestAnimationFrame(()=>opener.current?.focus())}
function persist(next){try{localStorage.setItem(KEY,JSON.stringify(next));setNotes(next);return true}catch{setError('保存できませんでした。入力内容は残っています。');return false}}
function save(){if(!draft.trim())return;const n=editing?{...notes.find(n=>n.id===editing),text:draft.trim(),title:draft.trim().split('\n')[0].slice(0,28)}:{id:crypto.randomUUID(),text:draft.trim(),title:draft.trim().split('\n')[0].slice(0,28),date:new Date().toISOString(),group:'Unsorted',origin:draftOrigin,x:450+(notes.length%4)*45,y:170+(notes.length%5)*50};if(!persist(editing?notes.map(a=>a.id===editing?n:a):[n,...notes]))return;setDraft('');setDraftOrigin(null);setEditing(null);setSelected(n.id);setPage('Notes');setQuery('');setFilter(null);close();setToast('Saved on this device');}
useEffect(()=>{function key(e){if(e.isComposing)return;if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setQuery('');open('search')}if((e.metaKey||e.ctrlKey)&&e.shiftKey&&e.key.toLowerCase()==='n'){e.preventDefault();open('capture')}if(e.key==='Escape'){if(modal)close();else setSelected(null)}}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[modal]);
useEffect(()=>{if(!modal)return;function trap(e){if(e.key!=='Tab')return;const nodes=[...document.querySelectorAll('.dialog button:not(:disabled), .dialog input, .dialog textarea, .dialog a')].filter(n=>n.offsetParent!==null);if(!nodes.length)return;const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}document.addEventListener('keydown',trap);return()=>document.removeEventListener('keydown',trap)},[modal]);
function navigate(p){setPage(p);setFilter(null);setQuery('');setSelected(null)}
function focusNote(id){setSelected(id);setModal(null);const n=notes.find(n=>n.id===id);if(n)setView({x:500-n.x,y:370-n.y,z:1});}
function zoom(delta){setView(v=>({...v,z:Math.max(.55,Math.min(1.9,v.z+delta))}))}
function exportNotes(){const a=document.createElement('a'),u=URL.createObjectURL(new Blob([JSON.stringify(notes,null,2)],{type:'application/json'}));a.href=u;a.download='pure-notes.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);setToast('Notes exported')}
function stashDraft(){if(draft.trim()){try{const old=read('pure.draft.history',[]);localStorage.setItem('pure.draft.history',JSON.stringify([...old,{text:draft,origin:draftOrigin,editing}].slice(-10)))}catch{}}}
function recoverDraft(){const old=read('pure.draft.history',[]);if(!old.length){setToast('No earlier draft');return;}const d=old.pop();stashDraft();setDraft(d.text);setDraftOrigin(d.origin||null);setEditing(d.editing||null);open('capture');}
function editNote(){stashDraft();setDraftOrigin(active.origin||null);setEditing(active.id);setDraft(active.text);open('capture')}
function makeDraft(){stashDraft();setDraftOrigin({type:'outline',sourceIds:[active.id,...linked.map(n=>n.id)]});setDraft(`考えの中心\n\n${active.text}\n\n大切にしたいこと\n\n\n最初に試すこと\n\n\n元になったメモ\n${[active,...linked].map(n=>'・'+n.title).join('\n')}`);setEditing(null);open('capture');setToast('Editable outline · AI is not connected')}
return <div className="app">
{boot&&<div className="boot" aria-hidden="true"><Mark/><span>p u r e .</span><div className="boot-line"/></div>}
<aside className="sidebar"><div className="traffic" aria-hidden="true"><i/><i/><i/></div><button className="brand" onClick={()=>navigate('Notes')} aria-label="pure home"><Mark/><span>pure.</span></button><div className="workspace-label">PERSONAL SPACE</div><nav>{[[FileTextIcon,'Notes'],[LayersIcon,'Collections'],[MagnifyingGlassIcon,'Search']].map(([Icon,name])=><button key={name} className={'nav-item '+(page===name?'active':'')} onClick={()=>name==='Search'?open('search'):navigate(name)}><Icon/><span>{name}</span>{name==='Search'&&<kbd>⌘K</kbd>}</button>)}</nav><button className="new-note" onClick={()=>open('capture')}><PlusIcon/>New note<span>↗</span></button><div className="sidebar-foot"><span className="device-status"><i/> On this device</span><button className="nav-item" onClick={()=>open('settings')}><GearIcon/><span>Settings</span></button><div className="prototype-tag">pure. / memory interface 03</div></div></aside>
<main className={'main '+(active?'with-detail':'')}><header className="topbar"><div className="heading-group"><h1>{page}</h1>{page==='Collections'&&<div className="segmented"><button className={mode==='list'?'chosen':''} onClick={()=>{setMode('list');setSelected(null)}}><GridIcon/>Insights</button><button className={mode==='graph'?'chosen':''} onClick={()=>setMode('graph')}><Share2Icon/>Graph</button></div>}</div><button className="icon-button" aria-label="Search notes" onClick={()=>open('search')}><MagnifyingGlassIcon/></button></header>
{page==='Collections'&&mode==='graph'?<><div className="graph-heading"><div><span className="eyebrow">YOUR THOUGHTS, CONNECTED</span><p>{active?active.group:'A little space for everything.'}</p></div><button className="text-button" onClick={()=>{setView({x:0,y:0,z:1});setSelected(null)}}><EnterFullScreenIcon/>Reset view</button></div><div className="graph-wrap" ref={graphRef}><SynapseField reduced={reduced}/><div className="graph-telemetry" aria-hidden="true"><span>memory.field</span><span>{String(notes.length).padStart(3,'0')} fragments / {edges.length} sample links</span></div>
<svg className="graph" viewBox="0 0 1000 760" role="group" aria-label="Interactive note connections" onWheel={e=>{zoom(e.deltaY>0?-.055:.055)}} onPointerDown={e=>{if(e.target.closest('[data-node]'))return;e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,v:view};}} onPointerMove={e=>{if(!drag.current)return;const bounds=e.currentTarget.getBoundingClientRect(),s=1000/bounds.width;setView({...drag.current.v,x:drag.current.v.x+(e.clientX-drag.current.x)*s,y:drag.current.v.y+(e.clientY-drag.current.y)*s})}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}>
<defs><radialGradient id="atmosphere"><stop stopColor="#476981" stopOpacity=".18"/><stop offset="1" stopColor="#182737" stopOpacity="0"/></radialGradient><filter id="soft"><feGaussianBlur stdDeviation="2"/></filter></defs><ellipse cx="470" cy="350" rx="420" ry="310" fill="url(#atmosphere)"/>
<g transform={`translate(${500+view.x} ${380+view.y}) scale(${view.z}) translate(-500 -380)`} className="graph-space">
<path className="liquid-trace" d="M80 510C100 270 750 650 710 200S180 170 440 420S870 310 920 130"/>
{Array.from({length:48},(_,i)=>{const x=65+(i*137%870),y=70+(i*79%635);return <g key={i} className="distant" aria-hidden="true"><circle cx={x} cy={y} r="1.7"/><path d={`M${x} ${y}l${(i%2?1:-1)*(25+i%60)} ${30+i%35}`}/></g>})}
{edges.map(([a,b],i)=>{const n=notes.find(n=>n.id===a),m=notes.find(n=>n.id===b);if(!n||!m)return null;const lit=[a,b].includes(hover||selected);return <path key={i} className={'edge '+(lit?'lit':'')+' '+(i%4===0?'suggested':'')} d={`M${n.x} ${n.y}Q${(n.x+m.x)/2+20} ${(n.y+m.y)/2-25} ${m.x} ${m.y}`}/>})}
{[{x:85,y:85,t:'SMALL PLEASURES'},{x:750,y:93,t:'FILMS & STORIES'},{x:735,y:735,t:'THINGS TO MAKE'},{x:90,y:715,t:'QUIET PLACES'}].map(g=><text key={g.t} className="cluster-label" x={g.x} y={g.y}>{g.t}</text>)}
{notes.map((n,i)=>{const sel=n.id===selected,near=linked.some(l=>l.id===n.id),left=n.x>780;return <g key={n.id} data-node="true" role="button" tabIndex="0" aria-label={'Open '+n.title} aria-pressed={sel} className={'node '+(sel?'selected':'')+' '+(near?'related':'')} transform={`translate(${n.x} ${n.y})`} onClick={()=>setSelected(n.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(n.id)}}} onMouseEnter={()=>setHover(n.id)} onMouseLeave={()=>setHover(null)}><circle className="hit-area" r="23"/><circle className="halo" r={sel?28:12}/><circle className="node-ring" r={sel?17:7}/><circle className="node-dot" r={sel?8:3.4}/><text x={left?-17:sel?35:17} y="5" textAnchor={left?'end':'start'} className="node-label">{n.title.length>18?n.title.slice(0,18)+'…':n.title}</text>{sel&&<text x="35" y="26" className="node-caption">SELECTED MEMORY</text>}</g>})}</g></svg>
<div className="graph-corner tl"/><div className="graph-corner br"/>
<div className="graph-bottom"><div className="legend"><span><i/>Connection</span><span><i className="dashed"/>Suggested</span><small>Sample connections</small></div><div className="zoom"><button aria-label="Zoom out" onClick={()=>zoom(-.15)}><MinusIcon/></button><span>{Math.round(view.z*100)}%</span><button aria-label="Zoom in" onClick={()=>zoom(.15)}><PlusIcon/></button><button aria-label="Fit graph" onClick={()=>setView({x:0,y:0,z:1})}><EnterFullScreenIcon/></button></div></div></div></>:
page==='Collections'?<Collections notes={notes} originals={[...seeds,...musicSamples]} reduced={reduced} onNote={id=>setSelected(id)} onGraph={id=>{setMode('graph');setSelected(id||null);setView({x:0,y:0,z:1})}} onAction={(action,category)=>{stashDraft();setDraft(`${action.title}\n\n${action.why}\n\n${action.steps.join('\n\n')}\n\n元になったメモ\n${action.sources.map(id=>'・'+notes.find(n=>n.id===id)?.title).join('\n')}`);setDraftOrigin({type:'suggested-action',category,sourceIds:action.sources});setEditing(null);open('capture')}}/>:
<div className="notes-page"><div className="notes-intro"><div><span className="eyebrow">A LITTLE OF EVERYTHING</span><p>{filter||'Leave a thought here.'}</p></div>{filter&&<button className="text-button" onClick={()=>setFilter(null)}>All notes<Cross2Icon/></button>}</div><button className="inline-compose" onClick={()=>open('capture')}><Pencil1Icon/><span>What's on your mind?</span><kbd>⌘ ⇧ N</kbd></button>{shown.length===0?<div className="empty"><Mark/><h2>A space to begin.</h2><p>ひとことでも、リンクだけでも。</p><button className="primary" onClick={()=>open('capture')}>Write a note</button></div>:<div className="timeline">{shown.map((n,i)=><React.Fragment key={n.id}>{(i===0||new Date(shown[i-1].date).toLocaleDateString()!==new Date(n.date).toLocaleDateString())&&<h3 className="date-label">{new Date(n.date).toLocaleDateString('en-US',{month:'long',day:'numeric'})}</h3>}<button className={'note-row '+(selected===n.id?'selected':'')} onClick={()=>setSelected(n.id)}><time>{new Date(n.date).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}</time><div><p>{n.text}</p><span className="note-meta"><FileTextIcon/>{n.group==='Unsorted'?'Note':n.group}<ArrowRightIcon/></span></div></button></React.Fragment>)}</div>}</div>}
</main>
{active&&<aside className="inspector" key={active.id}><header><span><FileTextIcon/>Note</span><button className="icon-button" aria-label="Close note" onClick={()=>setSelected(null)}><Cross2Icon/></button></header><div className="inspector-scroll"><div className="note-date"><ClockIcon/>{new Date(active.date).toLocaleDateString('en-US',{month:'short',day:'numeric'})}<span> / </span>{new Date(active.date).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}<button className="icon-button" aria-label="Edit note" onClick={editNote}><Pencil1Icon/></button></div><p className="original">{active.text}</p><div className="inspector-divider"/>{linked.length>0?<><span className="eyebrow">{active.origin?'SOURCE NOTES':'CONNECTION PREVIEW'} {!active.origin&&<span className="sample-badge">DEMO</span>}</span><p className="insight">{active.origin?'この下書きの材料になったメモです。提案と、自分で書いた感想を分けて残しています。':'サンプルのつながりを表示しています。ジャンルごとのまとめと次の一歩は、Collections → Insightsで確認できます。'}</p><h3 className="related-title">Related notes <span>{linked.length}</span></h3><div className="related-list">{linked.map(n=><button key={n.id} onClick={()=>setSelected(n.id)}><FileTextIcon/><span>{n.title}</span><ChevronRightIcon/></button>)}</div></>:<div className="no-connections"><Share2Icon/><h3>A new thought.</h3><p>このメモは保存済みです。<br/>AIの接続後に、関連を見つけられます。</p></div>}</div><footer className="inspector-footer"><button className="primary" onClick={makeDraft}><LightningBoltIcon/>Shape an idea</button><button className="text-button" onClick={()=>{setPage('Collections');setMode('graph');focusNote(active.id)}}><Share2Icon/>Explore from here</button></footer></aside>}
{toast&&<div className="toast" role="status"><CheckIcon/>{toast}</div>}
{modal&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section className={'dialog '+modal} role="dialog" aria-modal="true" aria-label={modal==='capture'?'Quick capture':modal==='search'?'Search notes':'Settings'}><header><div className="dialog-brand"><Mark/><span>pure.</span><i/>{modal==='capture'?'Capture':modal==='search'?'Search':'Settings'}</div><button className="escape" onClick={close}>esc</button></header>
{modal==='capture'?<><label className="sr-only" htmlFor="capture">Your note</label><textarea id="capture" ref={inputRef} value={draft} onChange={e=>setDraft(e.target.value)} placeholder="What's on your mind?" onKeyDown={e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter'&&!e.nativeEvent.isComposing){e.preventDefault();save()}}}/>{error&&<p className="error" role="alert">{error}</p>}<footer><span className="capture-hint">{draftOrigin?'Editable suggestion · your decision':'A thought. A link. Anything.'}</span><button className="primary" disabled={!draft.trim()} onClick={save}>Save note <kbd>⌘ ↵</kbd></button></footer></>:modal==='search'?<><div className="search-input"><MagnifyingGlassIcon/><input ref={inputRef} aria-label="Search your notes" placeholder="Find a thought…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="search-results">{notes.filter(n=>n.text.toLowerCase().includes(query.toLowerCase())).map(n=><button key={n.id} onClick={()=>{setPage('Notes');setFilter(null);setQuery('');focusNote(n.id)}}><FileTextIcon/><div><span>{n.title}</span><small>{n.group}</small></div><ArrowRightIcon/></button>)}{!notes.some(n=>n.text.toLowerCase().includes(query.toLowerCase()))&&<p className="empty-search">No matching notes.</p>}</div></>:<div className="settings-body"><span className="eyebrow">MAKE YOURSELF AT HOME</span><div className="setting-row"><div><h3>Reduced motion</h3><p>Keep transitions quiet.</p></div><button className={'toggle '+(reduced?'on':'')} role="switch" aria-checked={reduced} aria-label="Reduced motion" onClick={()=>setReduced(!reduced)}><i/></button></div><div className="setting-row"><div><h3>Your notes</h3><p>Saved in this browser on this device.</p></div><button className="text-button" onClick={exportNotes}><DownloadIcon/>Export</button></div><div className="setting-row"><div><h3>AI connection</h3><p>Not connected. Graph relationships use sample data.</p></div><span className="sample-badge">PREVIEW</span></div><div className="setting-row"><div><h3>Quick capture</h3><p>Available while this preview is focused.</p></div><kbd>⌘ ⇧ N</kbd></div><button className="text-button" onClick={recoverDraft}><ClockIcon/>Recover previous draft</button><p className="settings-note">UI prototype · メモはブラウザ内に保存されます。<br/>クラウド同期・AI解析・画像添付は未接続です。</p></div>}
</section></div>}
</div>}
createRoot(document.getElementById('root')).render(<App/>);
